name: Deploy DevTracker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: syadav49/devtracker-api:latest
          platforms: linux/amd64

      - name: Build and push UI image
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          push: true
          tags: syadav49/devtracker-ui:latest
          platforms: linux/amd64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy configuration files
        uses: appleboy/scp-action@master
        with:
          host: 5.181.217.47
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,ui/nginx.conf,nginx-host.conf"
          target: "/root/devtracker"
          strip_components: 0

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 5.181.217.47
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/devtracker
            
            # Stop and remove existing containers
            docker-compose down
            
            # Pull latest images
            docker-compose pull
            
            # Setup Nginx configuration
            cp nginx-host.conf /etc/nginx/sites-available/devtracker
            ln -sf /etc/nginx/sites-available/devtracker /etc/nginx/sites-enabled/
            nginx -t && systemctl reload nginx
            
            # Start containers
            docker-compose up -d
            
            # Setup SSL if not already configured
            if [ ! -f /etc/letsencrypt/live/devtracker.letsprogram.in/fullchain.pem ]; then
              certbot --nginx -d devtracker.letsprogram.in --non-interactive --agree-tos -m your-email@example.com
            fi
